version: '3.8'

services:
  todo-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todo-db
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # Map port 1433 for SQL Server
    volumes:
        - sql-data:/var/opt/mssql         # persist database
        - ./infrastructure/sql-scripts:/init             # bind mount init scripts
    entrypoint: /bin/bash -c "/opt/mssql/bin/sqlservr & /init/init.sh && wait"
    restart: unless-stopped
  todo-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.App.Api.Todo
    ports:
      - "8081:8080" # Map port 8080 in the container to port 8080 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__TodoDb=${ConnectionStrings__TodoDb}
    depends_on:
      - todo-db
  app-web-client:
    build:
      context: .
      dockerfile: docker/Dockerfile.App.Web.Client
    ports:
      - "8080:8080" # Map port 8080 in the container to port 8080 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - AzureEntra:ClientSecret=${AZURE_ENTRA_CLIENT_SECRET}
    depends_on:
      - todo-api

volumes:
  sql-data: