version: "3.8"

services:
  todo-db:
    image: postgres:16
    container_name: todo-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong!Pass123
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./infra/tools/pg-init-scripts:/docker-entrypoint-initdb.d # auto-executes scripts on init
    restart: unless-stopped
  todo-api:
    build:
      context: .
      dockerfile: src/apps/App.Api.Todo/dockerfile
    ports:
      - "8081:8080" # Map port 8080 in the container to port 8080 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__TodoDb=${Todo_Api_ConnectionStrings__TodoDb}
      - EnableAuthentication=${Todo_Api_Enable_Authentication}
    depends_on:
      - todo-db
  app-web-client:
    build:
      context: .
      dockerfile: src/apps/App.Web.Client/dockerfile
    ports:
      - "8080:8080" # Map port 8080 in the container to port 8080 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - AzureEntra:ClientSecret=${Web_Client_AZURE_ENTRA_CLIENT_SECRET}
      - TodoApiBaseUrl=http://todo-api:8080 # Use service name for internal communication
      - AzureEntra:RedirectUri=${Web_client_Azure_Entra_Redirect_Uri}
      - TodoApi:BaseUrl=${Web_Client_Todo_Api_Base_Url}
    depends_on:
      - todo-api

volumes:
  pg-data:
