version: "3.8"

services:
  todo-db:
    image: postgres:16
    container_name: todo-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong!Pass123
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./infrastructure/pg-init-scripts:/docker-entrypoint-initdb.d # auto-executes scripts on init
    restart: unless-stopped
  todo-api:
    build:
      context: .
      dockerfile: apps/App.Api.Todo/Dockerfile.App.Api.Todo
    ports:
      - "8081:8080" # Map port 8080 in the container to port 8080 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__TodoDb=${ConnectionStrings__TodoDb}
    depends_on:
      - todo-db
  app-web-client:
    build:
      context: .
      dockerfile: apps/App.Web.Client/Dockerfile.App.Web.Client
    ports:
      - "8080:8080" # Map port 8080 in the container to port 8080 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - AzureEntra:ClientSecret=${AZURE_ENTRA_CLIENT_SECRET}
    depends_on:
      - todo-api

volumes:
  pg-data:
