// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Api.Todo.Models;

public partial class TodoTask
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    public string Notes { get; set; }

    public bool IsCompleted { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public int ToDoListId { get; set; }

    public int? ParentTaskId { get; set; }

    [InverseProperty("ParentTask")]
    public virtual ICollection<TodoTask> InverseParentTask { get; set; } = new List<TodoTask>();

    [ForeignKey("ParentTaskId")]
    [InverseProperty("InverseParentTask")]
    public virtual TodoTask ParentTask { get; set; }

    [ForeignKey("ToDoListId")]
    [InverseProperty("Tasks")]
    public virtual ToDoList ToDoList { get; set; }

    [ForeignKey("TaskId")]
    [InverseProperty("Tasks")]
    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}