// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Api.Todo.Models;

public partial class ToDoList
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    [Required]
    [StringLength(255)]
    public string UserId { get; set; }

    [InverseProperty("ToDoList")]
    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}