# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build 
WORKDIR /src

# Copy the rest of the source code
COPY [".version" , ".version"]
COPY ["Directory.Build.props" , "Directory.Build.props"]
COPY ["./src/apps/App.Web.Client/" , "apps/App.Web.Client/"]
COPY ["./src/shared/App.Common.Abstractions/" , "shared/App.Common.Abstractions/"]
COPY ["./src/shared/App.Common.Infrastructure/" , "shared/App.Common.Infrastructure/"]
COPY ["./src/shared/App.Common.Model/" , "shared/App.Common.Model/"]

# Publish the application
RUN dotnet publish "apps/App.Web.Client/App.Web.Client.csproj" -c Release -o /app/published /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine  
WORKDIR /app
COPY --from=build ./app/published .
ENTRYPOINT [ "dotnet", "App.Web.Client.dll" ]